version: "2"

services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    image: percona:5.7
    volumes:
      - /dev/shm/mysql-unim-dev:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: d8
      MYSQL_USER: d8
      MYSQL_PASSWORD: d8
      MYSQL_ROOT_PASSWORD: d8root
    restart: always
    networks:
      - back

networks:
  back:
    driver: bridge
