version: "2"

services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    image: percona:5.7
    environment:
      MYSQL_DATABASE: d6
      MYSQL_USER: d6
      MYSQL_PASSWORD: d6
      MYSQL_ROOT_PASSWORD: d6root
    restart: always
    networks:
      - back

networks:
  back:
    driver: bridge
